import { CreateDivisionDto, UpdateDivisionDto } from './dtos/division.dto';
import { CreateMatchDto, UpdateMatchDto } from './dtos/match.dto';
import { CreatePhaseDto, UpdatePhaseDto } from './dtos/phase.dto';
import { CreatePlayerDto, UpdatePlayerDto } from './dtos/player.dto';
import { CreateRoundDto, UpdateRoundDto } from './dtos/round.dto';
import { CreateScoreDto, UpdateScoreDto } from './dtos/score.dto';
import { CreateSongDto, UpdateSongDto } from './dtos/song.dto';
import { CreateStandingDto, UpdateStandingDto } from './dtos/standing.dto';
import { CreateTeamDto, UpdateTeamDto } from './dtos/team.dto';
import { CreateTournamentDto, UpdateTournamentDto } from './dtos/tournament.dto';
import { CreateMatchAssignmentDto, UpdateMatchAssignmentDto } from './dtos/match_assignment.dto';
import { CreateSetupDto, UpdateSetupDto } from './dtos/setup.dto';

export { CreateDivisionDto, UpdateDivisionDto };
export { CreateMatchDto, UpdateMatchDto };
export { CreatePhaseDto, UpdatePhaseDto };
export { CreatePlayerDto, UpdatePlayerDto };
export { CreateRoundDto, UpdateRoundDto };
export { CreateScoreDto, UpdateScoreDto };
export { CreateSongDto, UpdateSongDto };
export { CreateStandingDto, UpdateStandingDto };
export { CreateTeamDto, UpdateTeamDto };
export { CreateTournamentDto, UpdateTournamentDto };
export { CreateMatchAssignmentDto, UpdateMatchAssignmentDto };
export { CreateSetupDto, UpdateSetupDto };